export const SalesData=[
    {
        id:1,
        month:'Jan',
        sales:30000
    },
    {
        id:2,
        month:'Feb',
        sales:40000
    },
    {
        id:3,
        month:'Mar',
        sales:68000
    },
    {
        id:4,
        month:'Apr',
        sales:56000
    },
    {
        id:5,
        month:'May',
        sales:70000
    },
    {
        id:6,
        month:'June',
        sales:90000
    },
    {
        id:7,
        month:'July',
        sales:70000
    },
    {
        id:8,
        month:'Aug',
        sales:85000
    },
    {
        id:9,
        month:'Sep',
        sales:70000
    },
    {
        id:10,
        month:'Oct',
        sales:45000
    },
    {
        id:11,
        month:'Nov',
        sales:56000
    },
    {
        id:12,
        month:'Dec',
        sales:45000
    },
]